### PR TITLE
Feature header responsiveness

### PR DESCRIPTION
**Pull request by vsmedeiros**
- [x] Incorporating custom screen configurations to optimize the layout for smaller devices.
- [x] Improving the header logo's responsiveness.
- [x] "Burguer" dropdown menu.
- [x] Closing the dropdown menu when clicked outside or when inside a menu item.

### CODE REVIEW

**Comment by noams24** [comment]
@vsmedeiros Hi! Can you make that "קורסים" and "העלאת שאלה" buttons will become a Hamburger menu bar flat icon on small screen?
image
like in this project: 
https://zeon.studio/preview?project=nextplate
https://github.com/zeon-studio/nextplate/blob/main/src/layouts/partials/Header.tsx

**Comment by noams24** [comment]
@vsmedeiros Thanks!
By the way, do you know how to fix that if the user navigating between pages using Link component,
close the drop down?
In other words, set the value "isDropdownOpen" to false when navigating between routes?

**Comment by vsmedeiros** [comment]
> @vsmedeiros Thanks! By the way, do you know how to fix that if the user navigating between pages using Link component, close the drop down? In other words, set the value "isDropdownOpen" to false when navigating between routes?

@noams24 You're welcome! I'll aim to address this functionality later.

**Review by noams24 — APPROVED** [review]
Amazing work!

**Comment by vsmedeiros** [comment]
> Amazing work!

Pleased to make a contribution!

**Pull request merged**
